#ifndef NETWORKREQUESTLIB_GLOBAL_H
#define NETWORKREQUESTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKREQUESTLIB_LIBRARY)
#define NETWORKREQUESTLIB_EXPORT Q_DECL_EXPORT
#else
#define NETWORKREQUESTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKREQUESTLIB_GLOBAL_H
